script: |

  echo "🚀 Connected to EC2"

  rm -rf app

  git clone https://github.com/sowmya-rebbavarapu/node-app-deploy.git app

  cd app

  sudo docker system prune -f

  echo "📦 Building Docker image"

  sudo docker build -t idp-app .

  echo "🛑 Removing old container"

  sudo docker stop idp-container || true
  sudo docker rm idp-container || true

  echo "🚀 Starting new container"

  sudo docker run -d -p 3000:3000 \
    --name idp-container idp-app

  echo "✅ Deployment completed"